#!/bin/bash

if [ -f .env ] ; then . .env; fi
conda install mamba
mamba install anaconda-client conda-build boa
conda config --set anaconda_upload true
conda mambabuild \
        -m multipython.yaml \
        -c defaults \
        -c conda-forge \
        -c bioconda \
        -c kdm801 \
        --skip-existing \
        pkgs/acanthophis pkgs/seqhax pkgs/rmlint
