#!/bin/bash

set -e
if [ -f .env ] ; then source .env; fi
mamba install anaconda-client conda-build boa
conda config --set anaconda_upload true
conda mambabuild \
        -m multipython.yaml \
        -c defaults \
        -c conda-forge \
        -c bioconda \
        -c kdm801 \
        --skip-existing \
        $1
