{% set name = "datetime_truncate" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: aa194f04e6829c4bbf105c80a868955505e5f9c4830b0471ddca7d2ec6bf55c6

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - six
    - typing
  run:
    - python
    - six
    - typing

test:
  imports:
    - datetime_truncate
  requires:
    - nose >=1.2.1

about:
  home: "https://github.com/gaqzi/datetime_truncate"
  license: BSD
  license_family: BSD
  license_file: 
  summary: "Truncate datetime objects to a set level of precision"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
