{% set name = "seqhax" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kdm9/{{name}}/archive/{{version}}.tar.gz
  sha256: 13fc3fa44ee12ed08db7cb37e6e7bf592bc310eb706f4bc8db1c8c15988895cd

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - zlib
    - cmake
    - make
    - python
  run:
    - python

test:
  commands:
    - seqhax
    - pecheck-wrapper.py --help

about:
  home: https://github.com/sahib/rmlint
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Miscelanelous fasta/fastq sequence tools'
  description: |
    A seqtk-style toolkit for sequence analysis. By no means feature complete.
    In fact largely contains features other authors have not merged into their
    respective tools.
  dev_url: https://github.com/kdm9/seqhax
  doc_url: https://github.com/kdm9/seqhax#seqhax

extra:
  recipe-maintainers:
    - kdm9
