{% set name = "seqhax" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kdm9/{{name}}/archive/{{version}}.tar.gz
  sha256: 43c0a10f257068b4543c1f48567eac2fca428667de3aea16baaf0b35876615f0

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - htslib
    - zlib
    - cmake
    - make
    - python
    - openmp  # [linux]
    - llvm-openmp  # [osx]
  run:
    - python
    - openmp  # [linux]
    - llvm-openmp  # [osx]


test:
  commands:
    - seqhax
    - htshax
    - pecheck-wrapper.py --help

about:
  home: https://github.com/kdm9/seqhax
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Miscelanelous fasta/fastq sequence and htslib utilities'
  description: |
    A seqtk-style toolkit for sequence analysis. By no means feature complete.
    In fact largely contains features other authors have not merged into their
    respective tools.
  dev_url: https://github.com/kdm9/seqhax
  doc_url: https://github.com/kdm9/seqhax#seqhax

extra:
  recipe-maintainers:
    - kdm9
