# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "rmlint" %}
{% set version = "2.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sahib/{{name}}/archive/v{{version}}.tar.gz
  sha256: 10e72ba4dd9672d1b6519c0c94eae647c5069c7d11f1409a46e7011dd0c6b883

build:
  number: 0
  skip: True  # [win]
  script: scons --prefix=$PREFIX install


requirements:
  build:
    - {{ compiler('c') }}
    - scons
    - pkg-config
    - sphinx
  host:
    - glib
    - elfutils
  run:
    - glib
    - elfutils

test:
  commands:
    - rmlint --help

about:
  home: https://github.com/sahib/rmlint
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  summary: 'Extremely fast tool to remove duplicates and other lint from your filesystem'
  description: |
    rmlint finds space waste and other broken things on your filesystem and offers to remove it.
  doc_url: http://rmlint.rtfd.org/
  dev_url: https://github.com/sahib/rmlint

extra:
  recipe-maintainers:
    - kdmurray91
