{% set name = "Acanthophis" %}
{% set version = "0.1.13" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/kdm9/{{name}}/archive/{{version}}.tar.gz
  sha256: e21081199fac7a46ae12984087bdb878f5140005af8a342a7e09802373a6ed4b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{python}}
  run:
    - python
    - snakemake

about:
  home: https://github.com/kdm9/Acanthophis
  license: "Mozilla Public 2.0 (MPL 2.0)"
  license_family: MOZILLA
  license_file:  LICENSE
  summary: "A comprehensive, opinionated plant variant calling pipeline in Snakemake"
  doc_url: https://github.com/kdm9/Acanthophis
  dev_url: https://github.com/kdm9/Acanthophis 

extra:
  recipe-maintainers:
    - kdm9
