{% set name = "acanthophis" %}
{% set version = "0.1.16" %}
{% set sha = "755bbe419b06db49fa6185ae7155ddc8fa93fc4e16de1f240f101745046dccc1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{name}}-{{ version }}.tar.gz"
  sha256: "{{ sha }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{python}}
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python
    - snakemake

about:
  home: https://github.com/kdm9/Acanthophis
  license: "Mozilla Public 2.0 (MPL 2.0)"
  license_family: MOZILLA
  license_file:  LICENSE
  summary: "A comprehensive, opinionated plant variant calling pipeline in Snakemake"
  doc_url: https://github.com/kdm9/Acanthophis
  dev_url: https://github.com/kdm9/Acanthophis 

extra:
  recipe-maintainers:
    - kdm9
