{% set name = "acanthophis" %}
{% set version = "0.1.14" %}
{% set sha = "4bc89f00f6767a129022c03d45a9b776e862fc027f218f974a1e39e653a03e31" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{name}}-{{ version }}.tar.gz"
  sha256: "{{ sha }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{python}}
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python
    - snakemake

about:
  home: https://github.com/kdm9/Acanthophis
  license: "Mozilla Public 2.0 (MPL 2.0)"
  license_family: MOZILLA
  license_file:  LICENSE
  summary: "A comprehensive, opinionated plant variant calling pipeline in Snakemake"
  doc_url: https://github.com/kdm9/Acanthophis
  dev_url: https://github.com/kdm9/Acanthophis 

extra:
  recipe-maintainers:
    - kdm9
