{% set name = "Acanthophis" %}
{% set version = "0.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/kdm9/{{name}}/archive/{{version}}.tar.gz
  sha256: 35faa29f5aeec74d33255e4653a86cf7514af190d34a7da572822cbdd7bfcdd2 

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - snakemake

about:
  home: https://github.com/kdm9/Acanthophis
  license: "Mozilla Public 2.0 (MPL 2.0)"
  license_family: MOZILLA
  license_file:  LICENSE
  summary: "A comprehensive, opinionated plant variant calling pipeline in Snakemake"
  doc_url: https://github.com/kdm9/Acanthophis
  dev_url: https://github.com/kdm9/Acanthophis 

extra:
  recipe-maintainers:
    - kdm9
