# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "json-glib" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{name}}/{{".".join(version.split(".")[:2])}}/{{name}}-{{version}}.tar.xz
  sha256: a33d66c6d038bda46b910c6c6d59c4e15db014e363dc997a0414c2e07d134f24

build:
  number: 0
  skip: True  # [win]
  script:
    - echo WHICH PYTHON3 ; echo ; echo ; echo; which python3
    - python3 --version
    - meson setup --prefix $PREFIX _build .
    - meson compile -C _build
    - meson test -C _build
    - ninja -C _build install

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - meson
    - ninja
    - pkg-config
    - python
  host:
    - gobject-introspection
    - glib
    - gettext
  run:
    - glib
    - gettext
    - gobject-introspection

about:
  home: https://gitlab.gnome.org/GNOME/json-glib/
  license: LGPL-2.1
  license_family: LGPL
  license_file: COPYING
  summary: 'Extremely fast tool to remove duplicates and other lint from your filesystem'
  description: |
    rmlint finds space waste and other broken things on your filesystem and offers to remove it.
  doc_url: http://rmlint.rtfd.org/
  dev_url: https://github.com/sahib/rmlint

extra:
  recipe-maintainers:
    - kdmurray91
