name: conda-build

on: push

jobs:
  conda-build-all:
    # Name the Job
    name: Build all conda packages
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Checkout code
        uses: actions/checkout@v2

      - name: conda build all
        shell: bash -l {0}
        run: |
          conda config --set anaconda_upload false
          conda install conda-build anaconda-client
          mkdir -p CONDA_OUTPUT
          conda build --output-folder CONDA_OUTPUT/ \
              -c kdm801 -c conda-forge -c bioconda \
              --skip-existing \
              pkgs/*
          anaconda upload --label main CONDA_OUTPUT/*/*.tar.bz2
